"""empty message

Revision ID: 37c2dfb2173
Revises: 
Create Date: 2021-12-02 21:13:50.801449

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '37c2dfb2173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('password', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    ### end Alembic commands ###
